[workspace]
members = [
    "server"
]

[package]
name = "FairVote"
version = "0.1.0"
authors = ["ZickShen <zick-hd@foxmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"

[[bin]]
name = "server"
path = "server/src/main.rs"